development:
  adapter: mysql2
  database: portaldb_development
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASSWORD']%>
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  database: portaldb_test
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASSWORD']%>
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: portaldb
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASSWORD']%>
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

cucumber:
  <<: *test